version: '3'
services:
  web:
    build: .
    ports:
      - "33000:3000"
      - "3035:3035"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails-tutorial
    depends_on:
      - mysql
    tty: true
    stdin_open: true
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
      NODE_OPTIONS: "--max_old_space_size=2048"
  mysql:
    image: mysql:5.7.22
    command: mysqld --character-set-server=utf8mb4
    ports:
      - "127.0.0.1:33306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: rails_tutorial_development
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db/data/mysql:/var/lib/mysql
